---
- hosts: all_in_one
  become: yes
  roles:
    - common-vars
    - covercore-common
    - secrets
    - configure-server
    - supervisor
    - postgres
    - postgres-server
    - redis
    - django-application
    - django-static
    - django-runserver
    - celery
    - celery-beat
    - nginx
- hosts: web
  become: yes
  roles:
    - common-vars
    - covercore-common
    - secrets
    - configure-server
    - supervisor
    - postgres
    - redis
    - django-application
    - django-static
    - django-runserver
    - celery
    - celery-beat
    - nginx
    - aws-cli
    - database-s3-dump
